import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css"; 
import Head from "next/head"

const geistSans = localFont({
  src: "../fonts/GeistVF.woff", // Caminho relativo a layout.tsx
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff", // Caminho relativo a layout.tsx
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Meu E-commerce",
  description: "Generated by create next appa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
